name: Push Commit Notification

on:
  push:
    branches:
      - main
      - develop

jobs:
  notify_on_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install jq
        
      - name: Call API on push
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
          COMMIT_SHA: ${{ github.event.after }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          # コミットSHAを最初の7文字に短縮
          short_sha=$(echo "$COMMIT_SHA" | cut -c1-7)
          
          commit_author="Committed by: $COMMIT_AUTHOR"
          
          # GitHubリポジトリのURLを修正してください
          commit_url="https://github.com/your-github-username/your-repository-name/commit/$COMMIT_SHA"

          payload=$(jq -n --arg message "$COMMIT_MESSAGE" --arg author "$commit_author" --arg url "$commit_url" --arg sha "$short_sha" '{
            "to": "${{ secrets.GROUP_ID }}",
            "messages": [
              {
                "type":"flex",
                "altText":"新しいコミットがプッシュされました。",
                "contents": {
                  "type": "bubble",
                  "header": {
                    "type": "box",
                    "layout": "vertical",
                    "contents": [
                      {
                        "type": "text",
                        "text": "新しいコミットがプッシュされました",
                        "weight": "bold",
                        "size": "sm",
                        "color": "#d0d7e0"
                      },
                      {
                        "type": "text",
                        "text": $sha,
                        "color": "#666666",
                        "size": "xs",
                        "margin": "sm"
                      }
                    ],
                    "backgroundColor": "#141c21",
                    "paddingAll": "md"
                  },
                  "body": {
                    "type": "box",
                    "layout": "vertical",
                    "contents": [
                      {
                        "type": "text",
                        "text": $message,
                        "wrap": true,
                        "size": "sm",
                        "color": "#666666",
                        "action": {
                            "type": "uri",
                            "uri": $url
                        },
                        "decoration": "underline"
                      }
                    ]
                  },
                  "footer": {
                    "type": "box",
                    "layout": "vertical",
                    "contents": [
                      {
                        "type": "text",
                        "text": $author,
                        "size": "xs",
                        "color": "#666666"
                      }
                    ],
                    "alignItems": "flex-end",
                    "backgroundColor": "#F3F3F3"
                  }
                }
              }
            ]
          }')

          curl -v -X POST https://api.line.me/v2/bot/message/push \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -d "$payload"