name: Issue Created Webhook

on:
  issues:
    types: [opened]

jobs:
  call_api_on_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install jq
      - name: Call API when Issue is created
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          issue_number="# $ISSUE_NUMBER"
          issue_author="Created by: $ISSUE_AUTHOR"

          payload=$(jq -n --arg title "$ISSUE_TITLE" --arg body "$ISSUE_BODY" --arg number "$issue_number" --arg url "$ISSUE_URL" --arg author "$issue_author" '{
            "to": "C3b848f3f63653016a2b6a9f469f7f416",
            "messages": [
              {
                "type":"flex",
                "altText":"新しいIssueを作成しました。",
                "contents": {
                  "type": "bubble",
                  "header": {
                    "type": "box",
                    "layout": "horizontal",
                    "contents": [
                      {
                        "type": "box",
                        "layout": "vertical",
                        "contents": [],
                        "cornerRadius": "5000px",
                        "width": "16px",
                        "height": "16px",
                        "spacing": "none",
                        "margin": "none",
                        "backgroundColor": "#57ab5b",
                        "offsetTop": "2px"
                      },
                      {
                        "type": "box",
                        "layout": "vertical",
                        "contents": [
                          {
                            "type": "text",
                            "text": $title,
                            "color": "#d0d7e0",
                            "action": {
                              "type": "uri",
                              "label": "action",
                              "uri": $url
                            },
                            "wrap": true,
                            "decoration": "underline"
                          },
                          {
                            "type": "text",
                            "wrap": true,
                            "text": $number,
                            "color": "#666666"
                          }
                        ]
                      }
                    ],
                    "backgroundColor": "#141c21",
                    "alignItems": "flex-start",
                    "spacing": "md"
                  },
                  "body": {
                    "type": "box",
                    "layout": "vertical",
                    "contents": [
                      {
                        "type": "box",
                        "layout": "vertical",
                        "margin": "md",
                        "spacing": "none",
                        "contents": [
                          {
                            "type": "text",
                            "text": $body,
                            "wrap": true,
                            "color": "#666666",
                            "size": "sm"
                          }
                        ]
                      }
                    ]
                  },
                  "footer": {
                    "type": "box",
                    "layout": "vertical",
                    "contents": [
                      {
                        "type": "text",
                        "text": $author,
                        "size": "xs",
                        "color": "#666666"
                      }
                    ],
                    "alignItems": "flex-end",
                    "backgroundColor": "#F3F3F3"
                  }
                }
              }
            ]
          }')

          curl -v -X POST https://api.line.me/v2/bot/message/push \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -d "$payload"
