"""Add date_rule and other fields to Festival model

Revision ID: 1cf46dd7e08b
Revises: 
Create Date: 2025-12-01 11:00:11.962282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf46dd7e08b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('festivals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('access', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date_rule', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('festivals', schema=None) as batch_op:
        batch_op.drop_column('date_rule')
        batch_op.drop_column('access')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
