"""Add google_user_id

Revision ID: 2c20d621b832
Revises: 6eadd397a2c5
Create Date: 2026-01-21 19:53:59.817029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c20d621b832'
down_revision = '6eadd397a2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_user_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_users_google_user_id', ['google_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_google_user_id', type_='unique')
        batch_op.drop_column('google_user_id')

    # ### end Alembic commands ###
