"""add shared_favorites table

Revision ID: 2c7cc5296ba1
Revises: eff6061c8c8d
Create Date: 2026-04-23 14:27:35.498879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7cc5296ba1'
down_revision = 'eff6061c8c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('festival_ids', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_favorites_share_id'), ['share_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_favorites_share_id'))

    op.drop_table('shared_favorites')
    # ### end Alembic commands ###
