"""Add email column to User

Revision ID: 4715d9593dda
Revises: 1cf46dd7e08b
Create Date: 2025-12-08 13:44:59.828684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4715d9593dda'
down_revision = '1cf46dd7e08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('festivals', schema=None) as batch_op:
        batch_op.drop_column('access')
        batch_op.drop_column('date_rule')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    with op.batch_alter_table('festivals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_rule', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('access', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
