"""Add festival photos table

Revision ID: 60dfb5b35716
Revises: 2c20d621b832
Create Date: 2026-01-27 16:03:56.409684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60dfb5b35716'
down_revision = '2c20d621b832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('festival_photos',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('festival_id', sa.Integer(), nullable=False),
    # sa.Column('image_url', sa.String(length=255), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('user_diaries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['google_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('user_diaries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('festival_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('image', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('date', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('user_diaries_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_diaries_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('festival_photos')
    # ### end Alembic commands ###
