"""Initial migration based on models.py

Revision ID: 6eadd397a2c5
Revises: 
Create Date: 2026-01-19 17:50:48.655959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '6eadd397a2c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('user_diaries')
    # with op.batch_alter_table('festivals', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('access', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)

    # 既存データの修正: 空文字のemailをNULLに変換してユニーク制約違反を防ぐ
    op.execute("UPDATE users SET email = NULL WHERE email = ''")

    # カラムの存在確認
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('users')]

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_email', ['email'])
        if 'password' in columns:
            batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('festivals', schema=None) as batch_op:
        batch_op.drop_column('access')

    op.create_table('user_diaries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('festival_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('image', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('date', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('user_diaries_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_diaries_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
