"""Add userID and rename username column

Revision ID: eff6061c8c8d
Revises: a8673ec652f3
Create Date: 2026-02-06 18:57:14.665136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'eff6061c8c8d'
down_revision = 'a8673ec652f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]
    # インデックスのリストを取得
    indexes = [idx['name'] for idx in inspector.get_indexes('users')]
    # ユニーク制約のリストを取得 (MySQLではインデックスとして扱われることが多いが念のため)
    # unique_constraints = [const['name'] for const in inspector.get_unique_constraints('users')]

    # 1. まず userID を NULL許可 で追加 (存在しない場合のみ)
    if 'userID' not in columns:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('userID', sa.String(length=120), nullable=True))

    # 2. 既存の username (旧ID) を userID にコピー
    op.execute('UPDATE users SET userID = username')
    
    # 3. 既存の display_name を username (新表示名) にコピー (display_nameがある場合)
    if 'display_name' in columns:
        op.execute('UPDATE users SET username = display_name WHERE display_name IS NOT NULL AND display_name != ""')

    # 4. カラム属性の変更と制約の追加
    with op.batch_alter_table('users', schema=None) as batch_op:
        # userID を NULL不可 に変更
        batch_op.alter_column('userID', existing_type=sa.String(length=120), nullable=False)
        # username を NULL許可 に変更
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        
        # インデックス削除 (存在する場合のみ)
        if 'username' in indexes:
            batch_op.drop_index('username')
            
        # ユニーク制約追加
        try:
            batch_op.create_unique_constraint(None, ['userID'])
        except:
            pass

        if 'display_name' in columns:
            batch_op.drop_column('display_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]

    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'display_name' not in columns:
            batch_op.add_column(sa.Column('display_name', mysql.VARCHAR(length=120), nullable=True))
    
    # データを戻す (username -> display_name, userID -> username)
    if 'userID' in columns:
        op.execute('UPDATE users SET display_name = username')
        op.execute('UPDATE users SET username = userID')

    with op.batch_alter_table('users', schema=None) as batch_op:
        try:
            batch_op.drop_constraint(None, type_='unique')
        except:
            pass
        
        try:
            batch_op.create_index('username', ['username'], unique=True)
        except:
            pass

        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        
        if 'userID' in columns:
            batch_op.drop_column('userID')
    # ### end Alembic commands ###
